[package]
name = "studentreportcard_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
axum = "0.8.7"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"